import { Article, TagColor } from './types';

export const NAV_LINKS = [
  { label: 'TOOLS', href: '/tools' },
  { label: 'TUTORIALS', href: '/tutorials' },
  { label: 'ETHICS', href: '/ethics' },
  { label: 'COMMUNITY', href: '/community' },
];

export const HERO_TAGS = [
  '#GENERATIVE', '#SYNTHETIC', '#DIFFUSION', '#MODEL'
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Midjourney V7: The End of Photography?',
    category: 'BREAKING',
    author: 'Sarah Jenkins',
    date: 'OCT 24',
    imageUrl: 'https://picsum.photos/800/600?random=1',
    bgColor: TagColor.LIME,
  },
  {
    id: '2',
    title: 'How to Train Your Own LoRA Model',
    category: 'TUTORIAL',
    author: 'Devin K.',
    date: 'OCT 23',
    imageUrl: 'https://picsum.photos/800/600?random=2',
    bgColor: TagColor.PURPLE,
  },
  {
    id: '3',
    title: 'Design Systems for the AI Age',
    category: 'OPINION',
    author: 'M. Robson',
    date: 'OCT 22',
    imageUrl: 'https://picsum.photos/800/600?random=3',
    bgColor: TagColor.YELLOW,
  },
  {
    id: '4',
    title: 'The Legal Landscape of Copyright',
    category: 'LEGAL',
    author: 'Legal Eagle',
    date: 'OCT 21',
    imageUrl: 'https://picsum.photos/800/600?random=4',
    bgColor: TagColor.ORANGE,
  },
  {
    id: '5',
    title: 'Runway Gen-3 Alpha Review',
    category: 'REVIEW',
    author: 'Video Synth',
    date: 'OCT 20',
    imageUrl: 'https://picsum.photos/800/600?random=5',
    bgColor: TagColor.BLUE,
  },
  {
    id: '6',
    title: 'Prompt Engineering is Dead. Long Live Context.',
    category: 'ANALYSIS',
    author: 'AI Whisperer',
    date: 'OCT 19',
    imageUrl: 'https://picsum.photos/800/600?random=6',
    bgColor: TagColor.PINK,
  },
  {
    id: '7',
    title: 'Generative Fill: A Complete Guide',
    category: 'TUTORIAL',
    author: 'Adobe Expert',
    date: 'OCT 18',
    imageUrl: 'https://picsum.photos/800/600?random=7',
    bgColor: TagColor.PURPLE,
  },
  {
    id: '8',
    title: 'DALL-E 3 vs Midjourney: Ultimate Comparison',
    category: 'REVIEW',
    author: 'AI Compare',
    date: 'OCT 17',
    imageUrl: 'https://picsum.photos/800/600?random=8',
    bgColor: TagColor.BLUE,
  },
  {
    id: '9',
    title: 'The Rise of Synthetic Media in Advertising',
    category: 'ANALYSIS',
    author: 'Media Watch',
    date: 'OCT 16',
    imageUrl: 'https://picsum.photos/800/600?random=9',
    bgColor: TagColor.PINK,
  },
  {
    id: '10',
    title: 'Stable Diffusion XL: New Features Explained',
    category: 'BREAKING',
    author: 'Tech Reporter',
    date: 'OCT 15',
    imageUrl: 'https://picsum.photos/800/600?random=10',
    bgColor: TagColor.LIME,
  },
  {
    id: '11',
    title: 'Building a Custom Diffusion Model',
    category: 'TUTORIAL',
    author: 'ML Engineer',
    date: 'OCT 14',
    imageUrl: 'https://picsum.photos/800/600?random=11',
    bgColor: TagColor.PURPLE,
  },
  {
    id: '12',
    title: 'AI Art in Museums: A New Era',
    category: 'OPINION',
    author: 'Art Critic',
    date: 'OCT 13',
    imageUrl: 'https://picsum.photos/800/600?random=12',
    bgColor: TagColor.YELLOW,
  },
  {
    id: '13',
    title: 'ComfyUI Workflow Masterclass',
    category: 'TUTORIAL',
    author: 'Node Master',
    date: 'OCT 12',
    imageUrl: 'https://picsum.photos/800/600?random=13',
    bgColor: TagColor.PURPLE,
  },
  {
    id: '14',
    title: 'AI Model Training: Legal Implications',
    category: 'LEGAL',
    author: 'IP Lawyer',
    date: 'OCT 11',
    imageUrl: 'https://picsum.photos/800/600?random=14',
    bgColor: TagColor.ORANGE,
  },
  {
    id: '15',
    title: 'Generative AI in Game Development',
    category: 'ANALYSIS',
    author: 'Game Dev Pro',
    date: 'OCT 10',
    imageUrl: 'https://picsum.photos/800/600?random=15',
    bgColor: TagColor.PINK,
  },
];

export const MARQUEE_TEXT = "BREAKING NEWS +++ AI TAKES OVER PIXELS +++ NEW MODELS RELEASED +++ GENERATIVE FILL IS MAGIC +++ ";
